# Generated by Django 4.2.5 on 2023-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
